src/Entity/Products.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ApiResource
 * @ORM\Entity(repositoryClass="App\Repository\ProductsRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Products
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Brands", inversedBy="products")
     */
    private $brand;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categories", inversedBy="products")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $img;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateAdded;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"name"})
     */
    private $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ProductReviews", mappedBy="product")
     * @ORM\OrderBy({"date" = "DESC"})
     */
    private $productReviews;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ProductOrder", mappedBy="product")
     */
    private $productOrders;

    public function __construct()
    {
        $this->productReviews = new ArrayCollection();
        $this->productOrders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getBrand(): ?Brands
    {
        return $this->brand;
    }

    public function setBrand(?Brands $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getCategory(): ?Categories
    {
        return $this->category;
    }

    public function setCategory(?Categories $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): self
    {
        $this->img = $img;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function updatedTimestamps(): void
    {
        if ($this->getDateAdded() === null) {
            $this->setDateAdded(new \DateTime('now'));
        }
    }

    public function getDateAdded(): ?\DateTimeInterface
    {
        return $this->dateAdded;
    }

    public function setDateAdded(\DateTimeInterface $dateAdded): self
    {
        $this->dateAdded = $dateAdded;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }


    public function getAvgProductReviews(): float
    {
        $productReviews = $this->getProductReviews();
        $avgRating = 0.0;
        foreach ($productReviews as $review) {
            $avgRating += $review->getRating();
        }
        $avgRating = sprintf("%.2f", ($avgRating / max(count($productReviews), 1)));

        return $avgRating;
    }

    /**
     * @return Collection|ProductReviews[]
     */
    public function getProductReviews(): Collection
    {
        return $this->productReviews;
    }

    public function getTotalRating($stars): float
    {
        return count(
            $this->getProductReviews()->filter(
                function (ProductReviews $productReviews) use ($stars) {
                    return $productReviews->getRating() == $stars;
                }
            )
        );
    }

    public function addProductReview(ProductReviews $productReview): self
    {
        if (!$this->productReviews->contains($productReview)) {
            $this->productReviews[] = $productReview;
            $productReview->setProduct($this);
        }

        return $this;
    }

    public function removeProductReview(ProductReviews $productReview): self
    {
        if ($this->productReviews->contains($productReview)) {
            $this->productReviews->removeElement($productReview);
            // set the owning side to null (unless already changed)
            if ($productReview->getProduct() === $this) {
                $productReview->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ProductOrder[]
     */
    public function getProductOrders(): Collection
    {
        return $this->productOrders;
    }

    public function addProductOrder(ProductOrder $productOrder): self
    {
        if (!$this->productOrders->contains($productOrder)) {
            $this->productOrders[] = $productOrder;
            $productOrder->setProduct($this);
        }

        return $this;
    }

    public function removeProductOrder(ProductOrder $productOrder): self
    {
        if ($this->productOrders->contains($productOrder)) {
            $this->productOrders->removeElement($productOrder);
            // set the owning side to null (unless already changed)
            if ($productOrder->getProduct() === $this) {
                $productOrder->setProduct(null);
            }
        }

        return $this;
    }
}

src/Controller/ListController.php
<?php

namespace App\Controller;

use App\Entity\Brands;
use App\Entity\Categories;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ListController extends AbstractController
{
    /**
     * @Route("/category/{slug}", name="list")
     * @param Categories $category
     * @return Response
     */
    public function listProducts(Categories $category)
    {
        $allCategories = $this->getDoctrine()->getRepository(Categories::class)->findAll();
        $allbrands = $this->getDoctrine()->getRepository(Brands::class)->findAll();

        return $this->render(
        'list/index.html.twig',
        [
        'current_category' => $category,
        'all_categories' => $allCategories,
        'brands' => $allbrands,
        ]
        );
    }
}

templates/list/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} List{% endblock %}

{% block body %}
    <div id="breadcrumb" class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="breadcrumb-tree">
                        <li><a href="{{ path('homepage') }}">Home</a></li>
                        <li><a href="/category/{{ current_category.slug }}">
                                {{ current_category.name }} ({{ current_category.products|length }} result(s))
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="section">
        <div class="container">
            <div class="row">
                <div id="aside" class="col-md-3">
                    <div class="aside">
                        <h3 class="aside-title">Categories</h3>
                        <div class="checkbox-filter">
                            {% for cat in all_categories %}
                                <div class="input-checkbox">
                                    <input type="checkbox" id="{{ cat.name }}"
                                            {% if current_category.name == cat.name %} checked {% endif %}>
                                    <label for="category-1">
                                        <span></span>
                                        {{ cat.name }}
                                        <small>({{ cat.products|length }})</small>
                                    </label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="aside">
                        <h3 class="aside-title">Price</h3>
                        <div class="price-filter">
                            <div id="price-slider"></div>
                            <div class="input-number price-min">
                                <input id="price-min" type="number" value="0.00">
                                <span class="qty-up">+</span>
                                <span class="qty-down">-</span>
                            </div>
                            <span>-</span>
                            <div class="input-number price-max">
                                <input id="price-max" type="number" value="0.00">
                                <span class="qty-up">+</span>
                                <span class="qty-down">-</span>
                            </div>
                        </div>
                    </div>
                    <div class="aside">
                        <h3 class="aside-title">Brand</h3>
                        <div class="checkbox-filter">
                            {% for brand in brands %}
                                <div class="input-checkbox">
                                    <input type="checkbox" id="{{ brand.name }}">
                                    <label for="{{ brand.name }}">
                                        <span></span>
                                        {{ brand.name }}
                                        <small>({{ brand.products|length }})</small>
                                    </label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div id="store" class="col-md-9">
                    <div class="store-filter clearfix">
                        <div class="store-sort">
                            <label>
                                Sort By:
                                <select class="input-select">
                                    <option value="0">Popular</option>
                                    <option value="1">Position</option>
                                </select>
                            </label>

                            <label>
                                Show:
                                <select class="input-select">
                                    <option value="0">20</option>
                                    <option value="1">50</option>
                                </select>
                            </label>
                        </div>
                        {#                        <ul class="store-grid">#}
                        {#                            <li class="active"><i class="fa fa-th"></i></li>#}
                        {#                            <li><a href="#"><i class="fa fa-th-list"></i></a></li>#}
                        {#                        </ul>#}
                    </div>
                    <div class="row">
                        {% for product in current_category.products %}
                            <div class="col-md-4 col-xs-6">
                                <div class="product">
                                    <div class="product-img">
                                        <img src="{{ product.img }}" alt="">
                                        <div class="product-label">
                                            {#                                        <span class="sale">-30%</span>#}
                                            {#                                        <span class="new">NEW</span>#}
                                        </div>
                                    </div>
                                    <div class="product-body">
                                        <p class="product-category">{{ product.category.name }}</p>
                                        <h3 class="product-name"><a
                                                    href="{{ path('view_product', {'slug': product.slug}) }}">{{ product.name }}</a>
                                        </h3>
                                        <h4 class="product-price">${{ product.price|number_format(2,'.','') }}
                                            {#                                        <del class="product-old-price">$990.00</del>#}
                                        </h4>
                                        <div class="product-rating">
                                            {% for i in 1..5 %}
                                                {% if i <= product.avgProductReviews %}
                                                    <i class="fa fa-star"></i>
                                                {% else %}
                                                    <i class="fa fa-star-o"></i>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                        <div class="product-btns">
                                            <button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span
                                                        class="tooltipp">add to wishlist</span></button>
                                        </div>
                                    </div>
                                    <div class="add-to-cart">
                                        <add-to-cart-btn v-on:addproduct="updateCart"
                                                         :product="{{ product.id }}"></add-to-cart-btn>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="store-filter clearfix">
                        <span class="store-qty">Showing 20-100 products</span>
                        <ul class="store-pagination">
                            <li class="active">1</li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}